# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0021_auto_20170128_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color_l',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Color', to_field='name_color', verbose_name='Цвет')),
            ],
        ),
    ]
