# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170319_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='color',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
