# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170108_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='F:/python-projects/rezum/practice/mysite/static/media/img', verbose_name='Ссылка картинки'),
        ),
    ]
