# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170108_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='STATIC_ROOT/media/img', verbose_name='Ссылка картинки'),
        ),
    ]
