# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170110_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='/images/', verbose_name='Ссылка картинки'),
        ),
    ]
