# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 20:33
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20170124_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Комментарий'),
        ),
    ]
