# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 17:48
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20170124_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
